# Generated by Django 3.1.7 on 2021-04-04 16:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subway',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('schedule', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('site', models.URLField(blank=True)),
                ('photo', models.URLField(blank=True)),
                ('coordinates', models.JSONField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbook.category')),
                ('subway', models.ManyToManyField(blank=True, related_name='places', to='handbook.Subway')),
                ('tags', models.ManyToManyField(blank=True, related_name='places', to='handbook.Tag')),
            ],
            options={
                'db_table': 'place',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('dates', models.JSONField(blank=True)),
                ('age_restriction', models.CharField(blank=True, max_length=3, null=True)),
                ('image', models.URLField(blank=True)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('tags_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='handbook.place')),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('dates', models.JSONField(blank=True)),
                ('age_restriction', models.CharField(blank=True, max_length=3, null=True)),
                ('image', models.URLField(blank=True)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='handbook.place')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='handbook.Tag')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
