# Generated by Django 3.1.7 on 2021-04-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_auto_20210411_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['dates']},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='subway',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='events',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='image',
            new_name='photo',
        ),
    ]
