# Generated by Django 3.1.7 on 2021-04-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0005_auto_20210421_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
